### ISSUE TITLE
Confused about dataset split.

### ISSUE THREAD

**Issue by ZachL1** [Q-Future/Q-Align#23]
I am trying to follow Q-Align's experimental setting for experiments, but I encountered some problems when I processed the dataset split. I hope to get your confirmation:
1. I checked spaq and koniq under `playground/data/test_jsons` and `playground/data/training_sft`, and I found that they both missed some data. spaq:(8897+2224)/11125; koniq: (7046+2010)/10073. Why are you filtering out this data?
2. **There are 1844 same images in `train_kadid.json` and `test_kadid.json`.**
3. There are 982 images in `live.json`, while there should be only 779 in the original dataset (https://live.ece.utexas.edu/research/Quality/subjective.htm)

**Comment by zzc-1998** [comment]
We are still checking and may give some updates later.

1. As for the "koniq: (7046+2010)/10073", we use the official train-val-test split as indicated (https://github.com/subpic/koniq/blob/master/metadata/koniq10k_distributions_sets.csv). There are 1,000 validation images which is why train+test < 10073. 
2. For the limited number of missing images (4 for spaq and 17 for koniq),  we are still checking. We guess it might be because of some unexpected preprocessing failure or broken image files that are filtered out.
3. For the train_kadid.json and test_kadid.json, the uploaded files are wrong. We are preparing to upload the correct files.
4. For the live.json, please download the datarelease2 version at (https://live.ece.utexas.edu/research/Quality/subjective.htm). There are 982 images in this version.

**Comment by zzc-1998** [comment]
![image](https://github.com/Q-Future/Q-Align/assets/58689334/b58fefe0-7127-459a-8e87-48281326732c) number of images in live datarelease2

**Comment by ZachL1** [comment]
Thanks for the detailed answer, it makes everything clear.

Also, I noticed that a portion of the gt of images is missing from the [labels available to CSIQ](https://s2.smu.edu/~eclarson/csiq/csiq.DMOS.xlsx), however there are scores corresponding to these images in your csiq.json.

I got the CSIQ dataset from the following link and it seems to be official. (maybe?)
https://qualinet.github.io/databases/image/categorical_image_quality_csiq_database/

**Comment by zzc-1998** [comment]
We have checked the downloaded files. It might be because we downloaded the csiq database and found that there are only 750 images in total. 150 images for each of the distortion "awgn\blur\contrast\fnoise\jpeg\jpeg2000". We are not aware of what was wrong and we are still inspecting it.

**Comment by ZachL1** [comment]
> 3\. For the train_kadid.json and test_kadid.json, the uploaded files are wrong. We are preparing to upload the correct files.

I see that you have updated `training_sft/train_kadid.json` and `test_jsons/test_kadid.json`, should `training_sft/train_koniq_spaq_kadid.json` also be updated?

In addition, in view of the inappropriate split of the kadid dataset, can you please check and update the experimental result related to kadid in the report/paper? I hope to be able to reproduce the results based on the existing json files in this repo.

Thank you very much for your excellent work and efforts for IQA, much respect!
